### ISSUE TITLE
Error in test.py

### ISSUE THREAD

**Issue by hadarsh7798** [charlesq34/frustum-pointnets#116]
Hello, I am facing following issue when trying to run test.py. Please help me resolving this issue

Traceback (most recent call last):
  File "test.py", line 345, in <module>
    test_from_rgb_detection(FLAGS.output+'.pickle', FLAGS.output)
  File "test.py", line 227, in test_from_rgb_detection
    NUM_POINT, NUM_CHANNEL, from_rgb_detection=True)
  File "/content/drive/My Drive/frustum-pointnet/train/train_util.py", line 28, in get_batch
    num_point, num_channel)
  File "/content/drive/My Drive/frustum-pointnet/train/train_util.py", line 77, in get_batch_from_rgb_detection
    ps,rotangle,prob,onehotvec = dataset[idxs[i+start_idx]]
  File "/content/drive/My Drive/frustum-pointnet/train/provider.py", line 165, in __getitem__
    assert(cls_type in ['Car', 'Pedestrian', 'Cyclist'])
AssertionError

**Comment by super-fsy** [comment]
I have same problem
