### ISSUE TITLE
Anyone runs this repo with python3 successfully? 

### ISSUE THREAD

**Issue by sisrfeng** [charlesq34/frustum-pointnets#118]
tf_xxx_compile.sh specifies  /usr/local/lib/python2.7.
I am afraid that there remains more modify
> Being syntax compatible with Python 3 does not mean that the port to Python 3 is complete.

**Comment by AllenPu** [comment]
yes, and you have to revise all three sh files to your own python path and cuda path
i strongly encourage you to use tensorflow-gpu 1.8+python3.6 which can save a lot of trouble

**Comment by chaoyu1999** [comment]
@AllenPu  你好，你使用py3.6复现成功了吗？我使用py3.6的时候在**train/provider.py**中`import cPickle as pickle`的时候，显示py3不支持cPickle，于是我换成pickle但是在加载数据的时候出现了错误`Traceback (most recent call last):
  File "train/train.py", line 68, in <module>
    rotate_to_center=True, random_flip=True, random_shift=True, one_hot=True)
  File "/home/cy/F-PointNet/frustum-pointnets-master/train/provider.py", line 142, in __init__
    self.box2d_list = pickle.load(fp)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 2: ordinal not in range(128)
`，请问你是怎么解决的？

**Comment by GondorFu** [comment]
> @AllenPu 你好，你使用py3.6复现成功了吗？我使用py3.6的时候在**train/provider.py**中`import cPickle as pickle`的时候，显示py3不支持cPickle，于是我换成pickle但是在加载数据的时候出现了错误`Traceback (most recent call last): File "train/train.py", line 68, in <module> rotate_to_center=True, random_flip=True, random_shift=True, one_hot=True) File "/home/cy/F-PointNet/frustum-pointnets-master/train/provider.py", line 142, in __init__ self.box2d_list = pickle.load(fp) UnicodeDecodeError: 'ascii' codec can't decode byte 0xb1 in position 2: ordinal not in range(128) `，请问你是怎么解决的？

这个你别用他提供的处理数据，自己处理一遍就行了
