### ISSUE TITLE
Evaluation test code: TabError: inconsistent use of tabs and spaces in indentation at line 231 in train/test.py

### ISSUE THREAD

**Issue by chowkamlee81** [charlesq34/frustum-pointnets#54]
Kindly help us to solve this indenttaion error @line 31 in train/test.py

Connected to pydev debugger (build 172.3968.37)
Traceback (most recent call last):
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/usr/share/pycharm/helpers/pydev/pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/usr/share/pycharm/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/administrator/Documents.orig/FileSystem/3D_Object_Detection/FrustrumNet/frustum-pointnets-master/train/test.py", line 231
    batch_output, batch_center_pred, \
                                     ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by kwea123** [comment]
Just change that tab into 4 spaces. Do the same for lines 236, 310, 317.

**Comment by chowkamlee81** [comment]
Done. It works..
