### ISSUE TITLE
UnknownError: exceptions.AttributeError: 'ConvexHull' object has no attribute 'volume'

### ISSUE THREAD

**Issue by zc-tx** [charlesq34/frustum-pointnets#6]
I am using tensorflow1.2.1 with cuda8.0, cudnn5.1 and python2.7.6 on Ubuntu14.04. The pointnet and pointnet2 runs normally, but when running frustum-pointnets, I get "UnknownError: exceptions.AttributeError: 'ConvexHull' object has no attribute 'volume'" error. Could you tell me what's wrong with my problem?The detail logs are as following.
**logs**
2018-04-20 17:03:09.080142: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1080
major: 6 minor: 1 memoryClockRate (GHz) 1.7335
pciBusID 0000:01:00.0
Total memory: 7.92GiB
Free memory: 7.51GiB
2018-04-20 17:03:09.080170: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2018-04-20 17:03:09.080178: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2018-04-20 17:03:09.080189: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0)
**** EPOCH 000 ****
2018-04-20 17:03:11.963841
2018-04-20 17:03:12.806428: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.AttributeError: 'ConvexHull' object has no attribute 'volume'
2018-04-20 17:03:12.836807: W tensorflow/core/framework/op_kernel.cc:1158] Unknown: exceptions.AttributeError: 'ConvexHull' object has no attribute 'volume'
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32, DT_FLOAT], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](add_1/_733, Slice_4/_735, mul_2/_737, Slice_6/_739, mul_3/_741, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4, _arg_Placeholder_5_0_5, _arg_Placeholder_6_0_6, _arg_Placeholder_7_0_7)]]
Traceback (most recent call last):
  File "train/train.py", line 376, in <module>
    train()
  File "train/train.py", line 201, in train
    train_one_epoch(sess, ops, train_writer)
  File "train/train.py", line 256, in train_one_epoch
    feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: exceptions.AttributeError: 'ConvexHull' object has no attribute 'volume'
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32, DT_FLOAT], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](add_1/_733, Slice_4/_735, mul_2/_737, Slice_6/_739, mul_3/_741, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4, _arg_Placeholder_5_0_5, _arg_Placeholder_6_0_6, _arg_Placeholder_7_0_7)]]
	 [[Node: Adam/update/NoOp/_1008 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_12590_Adam/update/NoOp", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'PyFunc_1', defined at:
  File "train/train.py", line 376, in <module>
    train()
  File "train/train.py", line 136, in train
    [tf.float32, tf.float32])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/script_ops.py", line 198, in py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_script_ops.py", line 38, in _py_func
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

UnknownError (see above for traceback): exceptions.AttributeError: 'ConvexHull' object has no attribute 'volume'
	 [[Node: PyFunc_1 = PyFunc[Tin=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT32, DT_FLOAT, DT_INT32, DT_FLOAT], Tout=[DT_FLOAT, DT_FLOAT], token="pyfunc_1", _device="/job:localhost/replica:0/task:0/cpu:0"](add_1/_733, Slice_4/_735, mul_2/_737, Slice_6/_739, mul_3/_741, _arg_Placeholder_3_0_3, _arg_Placeholder_4_0_4, _arg_Placeholder_5_0_5, _arg_Placeholder_6_0_6, _arg_Placeholder_7_0_7)]]
	 [[Node: Adam/update/NoOp/_1008 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_12590_Adam/update/NoOp", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by charlesq34** [comment]
Hi @zc-tx what is your scipy version?

you probably need to upgrade it.

**Comment by zc-tx** [comment]
@charlesq34 Thanks a lot, I have solved this problem by upgrading scipy.
