### ISSUE TITLE
mayavi problem

### ISSUE THREAD

**Issue by pyni** [charlesq34/frustum-pointnets#65]
i follow mayavi_install.sh  to install mayavi.
However, when i run test_drawline.py, it shows：
  File "test_drawline.py", line 2, in <module>
    from mayavi.mlab import *
  File "/usr/local/lib/python2.7/dist-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/engine_manager.py", line 12, in <module>
    from mayavi.preferences.api import preference_manager
  File "/usr/local/lib/python2.7/dist-packages/mayavi/preferences/api.py", line 4, in <module>
    from .preference_manager import preference_manager
  File "/usr/local/lib/python2.7/dist-packages/mayavi/preferences/preference_manager.py", line 29, in <module>
    from traitsui.api import View, Group, Item
  File "/usr/local/lib/python2.7/dist-packages/traitsui/api.py", line 36, in <module>
    from .editors.api import ArrayEditor
  File "/usr/local/lib/python2.7/dist-packages/traitsui/editors/__init__.py", line 23, in <module>
    from .api import ArrayEditor
  File "/usr/local/lib/python2.7/dist-packages/traitsui/editors/api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "/usr/local/lib/python2.7/dist-packages/traitsui/editors/code_editor.py", line 37, in <module>
    class ToolkitEditorFactory(EditorFactory):
  File "/usr/local/lib/python2.7/dist-packages/traitsui/editors/code_editor.py", line 49, in ToolkitEditorFactory
    mark_color = Color(0xECE9D8)
  File "/usr/local/lib/python2.7/dist-packages/traits/traits.py", line 522, in __call__
    return self.maker_function( *args, **metadata )
  File "/usr/local/lib/python2.7/dist-packages/traits/traits.py", line 1236, in Color
    return ColorTrait( *args, **metadata )
  File "/usr/local/lib/python2.7/dist-packages/traitsui/toolkit_traits.py", line 8, in ColorTrait
    return toolkit().color_trait(*args, **traits)
  File "/usr/local/lib/python2.7/dist-packages/traitsui/toolkit.py", line 109, in toolkit
    _toolkit = find_toolkit('traitsui.toolkits')
  File "/usr/local/lib/python2.7/dist-packages/pyface/base_toolkit.py", line 272, in find_toolkit
    toolkit = plugin.load()
  File "/home/yuan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2322, in load
    return self.resolve()
  File "/home/yuan/.local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2328, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/traitsui/qt4/__init__.py", line 25, in <module>
    import toolkit
  File "/usr/local/lib/python2.7/dist-packages/traitsui/qt4/toolkit.py", line 32, in <module>
    from .constants import screen_dx, screen_dy
  File "/usr/local/lib/python2.7/dist-packages/traitsui/qt4/constants.py", line 27, in <module>
    _palette = QtGui.QApplication.palette()
TypeError: palette() takes exactly one argument (0 given)

Any ideas please？

**Comment by pyni** [comment]
i have found the problem.

Moreover, i find another problem:
 
"mlab.show()" should be added before "return l", otherwise, nothing shows in the viewer. @charlesq34

**Comment by zhangxiaoya** [comment]
Hi, @pyni , how can you fix this issue?

**Comment by pyni** [comment]
我好像是装了个PySide就不报这个错了（不记得是PySide还是PyQt）

**Comment by HydrionSLight** [comment]
At first I have same problem with you, but when I finished installing PyQt and PySide,  there is another problem appeared. My operating environment is python2.7,ubuntu16.04,tensorflow1.13.1.related info as follows. 

Traceback (most recent call last):
  File "test_drawline.py", line 2, in <module>
    from mayavi.mlab import *
  File "/usr/local/lib/python2.7/dist-packages/mayavi/mlab.py", line 16, in <module>
    from mayavi.tools.camera import view, roll, yaw, pitch, move
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/camera.py", line 24, in <module>
    from .engine_manager import get_engine
  File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/engine_manager.py", line 13, in <module>
    from mayavi.core.registry import registry
  File "/usr/local/lib/python2.7/dist-packages/mayavi/core/registry.py", line 16, in <module>
    from mayavi.core.metadata import Metadata, import_symbol
  File "/usr/local/lib/python2.7/dist-packages/mayavi/core/metadata.py", line 11, in <module>
    from mayavi.core.pipeline_info import PipelineInfo
  File "/usr/local/lib/python2.7/dist-packages/mayavi/core/pipeline_info.py", line 12, in <module>
    from .utils import get_tvtk_dataset_name
  File "/usr/local/lib/python2.7/dist-packages/mayavi/core/utils.py", line 3, in <module>
    from vtk.numpy_interface import dataset_adapter as dsa
ImportError: No module named numpy_interface

Thx for any of your advice helping me solve this problem.^ ^

**Comment by jarvis-huang** [comment]
> i have found the problem.
> 
> Moreover, i find another problem:
> 
> "mlab.show()" should be added before "return l", otherwise, nothing shows in the viewer. @charlesq34

To solve blank window issue, add following to `test_drawline.py`
`import mayavi.mlab as mlab`
`mlab.show() # add before return l`

**Comment by hongyuli** [comment]
> At first I have same problem with you, but when I finished installing PyQt and PySide, there is another problem appeared. My operating environment is python2.7,ubuntu16.04,tensorflow1.13.1.related info as follows.
> 
> Traceback (most recent call last):
> File "test_drawline.py", line 2, in
> from mayavi.mlab import *
> File "/usr/local/lib/python2.7/dist-packages/mayavi/mlab.py", line 16, in
> from mayavi.tools.camera import view, roll, yaw, pitch, move
> File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/camera.py", line 24, in
> from .engine_manager import get_engine
> File "/usr/local/lib/python2.7/dist-packages/mayavi/tools/engine_manager.py", line 13, in
> from mayavi.core.registry import registry
> File "/usr/local/lib/python2.7/dist-packages/mayavi/core/registry.py", line 16, in
> from mayavi.core.metadata import Metadata, import_symbol
> File "/usr/local/lib/python2.7/dist-packages/mayavi/core/metadata.py", line 11, in
> from mayavi.core.pipeline_info import PipelineInfo
> File "/usr/local/lib/python2.7/dist-packages/mayavi/core/pipeline_info.py", line 12, in
> from .utils import get_tvtk_dataset_name
> File "/usr/local/lib/python2.7/dist-packages/mayavi/core/utils.py", line 3, in
> from vtk.numpy_interface import dataset_adapter as dsa
> ImportError: No module named numpy_interface
> 
> Thx for any of your advice helping me solve this problem.^ ^

I got the same problem because I installed the vtk by "apt-get install python-vtk"
As [discussed](https://stackoverflow.com/questions/15383666/installing-vtk-for-python) 

> VTK used to offer vtkpython binaries on their download page. However, they've dropped this since VTK-8.x.x

So my solution is to re-install the vtk by "pip install vtk"

**Comment by AllenPu** [comment]
> 我好像是装了个PySide就不报这个错了（不记得是PySide还是PyQt）

所以不需要单独安装mayavi这个了吗兄弟
