### ISSUE TITLE
python evaluate.py --data_path ...... error with to evaluate the 3D AP about SUNRGBD dataset 

### ISSUE THREAD

**Issue by shengrongjin** [charlesq34/frustum-pointnets#87]
I had generated 2D detector and made related .pickle files . However ,in the end , when I operated python evaluate.py --data_path ../sunrgbd_data/val_1002.zip.pickle --result_path test_results.pickle --from_rgb_detection . Such errors occured , 
Traceback (most recent call last):
  File "evaluate.py", line 29, in <module>
    TEST_DATASET = roi_seg_box3d_dataset.ROISegBoxDataset(npoints=2048, split='val', rotate_to_center=True, overwritten_data_path=FLAGS.data_path, from_rgb_detection=FLAGS.from_rgb_detection)
  File "/data/shengData/frustum-pointnets-master/sunrgbd/sunrgbd_detection/roi_seg_box3d_dataset.py", line 200, in __init__
    self.id_list, self.box2d_list, self.input_list, self.type_list, self.frustum_angle_list, self.prob_list = load_zipped_pickle(overwritten_data_path)

**Comment by shengrongjin** [comment]
The correct error is :
7689 6369

Construct GT boxes...
(2454, 10)
(2454,)

Construct PRED boxes...
Traceback (most recent call last):
  File "evaluate.py", line 101, in <module>
    print pred_all[1]
KeyError: 1

**Comment by smahesh2694** [comment]
Hi @shengrongjin did you solve the issue?

**Comment by zx970505** [comment]
> The correct error is :
> 7689 6369
> 
> Construct GT boxes...
> (2454, 10)
> (2454,)
> 
> Construct PRED boxes...
> Traceback (most recent call last):
> File "evaluate.py", line 101, in
> print pred_all[1]
> KeyError: 1



> The correct error is :
> 7689 6369
> 
> Construct GT boxes...
> (2454, 10)
> (2454,)
> 
> Construct PRED boxes...
> Traceback (most recent call last):
> File "evaluate.py", line 101, in
> print pred_all[1]
> KeyError: 1

HI, have you solved this problem?I have met it,too,how can i do?
